name: Track Issue Movement in Projects

on:
  project_card:
    types: [moved, created, deleted]

jobs:
  track-movement:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get column name
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Get column details
        column_url="${{ github.event.project_card.column_url }}"
        column_name=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$column_url" | jq -r '.name')

        echo "The issue is now in the column: $column_name"
