name: Issue Edited

on:
  issues:
    types: [edited]

jobs:
  issue-details:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log issue details
      run: echo "Issue #$ISSUE_NUMBER was edited. The current state is $ISSUE_STATE."
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_STATE: ${{ github.event.issue.state }}
