name: Update Issue Status to "In Review"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  update_issue_and_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2

      - name: Update Issue Status
        run: |
          ISSUE_NUMBER=$(echo "$GITHUB_BODY" | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
          if [ -n "$ISSUE_NUMBER" ]; then
            curl \
              -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"state":"In Review"}' \
              "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/issues/$ISSUE_NUMBER"
            echo "Issue status updated."
          else
            echo "No issue referenced in the pull request."
          fi
        env:
          GITHUB_BODY: ${{ github.event.pull_request.body }}

      - name: Assign Project and Member
        if: success()
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"project_id": ${{ secrets.ASSIGN_PROJECT_ID }}, "assignees": ["${{ secrets.ASSIGN_USERNAME }}"], "labels": ["${{ secrets.REPO_TEAM }}"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}}"
