name: Issue Status Check

on:
  issues:
    types: [opened, edited, transferred, labeled, unlabeled, closed, reopened]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get issue status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" > issue.json
        status=$(jq -r '.state' issue.json)
        echo "Issue status: $status"
