name: Log Issue and Project Details

on:
  issues:
    types: [opened, edited, reopened, closed, labeled, unlabeled, assigned, unassigned, milestoned, demilestoned]
  project_card:
    types: [created, edited, moved, deleted]

jobs:
  log-details:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log issue details
        if: github.event_name == 'issues'
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Labels: ${{ github.event.issue.labels.*.name }}"
          echo "Issue Assignees: ${{ github.event.issue.assignees.*.login }}"
          echo "Issue Milestone: ${{ github.event.issue.milestone.title }}"
          echo "Issue Creator: ${{ github.event.issue.user.login }}"
          echo "Issue Created at: ${{ github.event.issue.created_at }}"
          echo "Issue Updated at: ${{ github.event.issue.updated_at }}"
          echo "Issue Closed at: ${{ github.event.issue.closed_at }}"

      - name: Log project card details
        if: github.event_name == 'project_card'
        run: |
          echo "Project Card Action: ${{ github.event.action }}"
          echo "Card Content URL: ${{ github.event.project_card.content_url }}"
          echo "Card Column Name: ${{ github.event.project_card.column_name }}"
          echo "Card Created at: ${{ github.event.project_card.created_at }}"
          echo "Card Updated at: ${{ github.event.project_card.updated_at }}"
