name: Enforce Short Title

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  enforce_short_title:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Check Title Length
        id: title_check
        run: |
          if [ "$GITHUB_EVENT_NAME" == "issues" ]; then
            title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
            title_length=${#title}
            if [ "$title_length" -ge 40 ]; then
              echo "::error::Issue title length should be less than 40 characters."
              exit 1
            fi
          elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
            title_length=${#title}
            if [ "$title_length" -ge 40 ]; then
              echo "::error::Pull request title length should be less than 40 characters."
              exit 1
            fi
          fi
        continue-on-error: true

      - name: Update Issue/Pull Request Title
        if: failure()
        run: |
          if [ "$GITHUB_EVENT_NAME" == "issues" ]; then
            title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
            echo "Title for issue: $title"
            new_title=$(echo "$title" | cut -c -39)
            echo "New title for issue: $new_title"
            echo "NEW_TITLE=$new_title" >> $GITHUB_ENV
            gh issue edit "$NUMBER" --title "$new_title"
          elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
            echo "Title for pull request: $title"
            new_title=$(echo "$title" | cut -c -39)
            echo "New title for pull request: $new_title"
            echo "NEW_TITLE=$new_title" >> $GITHUB_ENV
            gh pr edit "$NUMBER" --title "$new_title"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }} # For issues
